### ISSUE TITLE
Pang updates

### ISSUE THREAD

**Issue by dyreschlock** [dyreschlock/pocket-extras#15]
Jotego has added some addition features to all of his cores, which includes JTpang.  Update the JTpang and JTblock stuff in pocket-extras and make sure that it works.

**Comment by espiox** [comment]
The core got updated to support Block Block properly, so arguably the jtblock core isn’t needed anymore (other than having separate cores for every game, but that’s a lot of upkeep!)

**Comment by dyreschlock** [comment]
Ah excellent.  That was on my mental list of things to check, but I'm glad you reminded me. :)

Less extras would be good.

**Comment by dyreschlock** [comment]
I think this is probably good.  The archive doesn't have dokaben2, so I'll send that.
