### ISSUE TITLE
Bubble Bobble Ultra Hack for jtbubl

### ISSUE THREAD

**Issue by espiox** [dyreschlock/pocket-extras#16]
I've got these files for the Bubble Bobble Ultra hack if you're interested (the ROM isn't included, obviously).

[jtbubl Bubble Bobble Ultra Hack.zip](https://github.com/dyreschlock/pocket-extras/files/13204153/jtbubl.Bubble.Bobble.Ultra.Hack.zip)

**Comment by dyreschlock** [comment]
Hrmm...  Do you have a MRA to make the rom?

**Comment by dyreschlock** [comment]
To make the rom, do you patch things using this romhack: https://www.romhacking.net/hacks/754

And then run the standard MRA on the resulting zip file?

**Comment by espiox** [comment]
"Super NES" on the Discord posted this MRA:

[Bubble Bobble Ultra mra.zip](https://github.com/dyreschlock/pocket-extras/files/13204583/Bubble.Bobble.Ultra.mra.zip)

I used the hack you linked, then used this MRA on that and that worked.

**Comment by dyreschlock** [comment]
Great, I got it working. :) Files and Instructions have been added.  Thanks!
