### ISSUE TITLE
Add Toaplan V2 Combination Core

### ISSUE THREAD

**Issue by dyreschlock** [dyreschlock/pocket-extras#20]
I've made a combination core for the Toaplan Version 2 Hardware arcade board that collects all of the currently released games.

Add it to the Pocket-Extras, and create a separate zip for it on release.

**Comment by espiox** [comment]
Thanks for pulling all this together!

**Comment by dyreschlock** [comment]
> Thanks for pulling all this together!

Yeah sure thing :). I mentioned this on Discord, but combining cores in this way can get around the 8 core limit in `data.json`. However, it does start to get messy when trying to figure out which game is where.

**Comment by dyreschlock** [comment]
This has been implemented, so I'm closing it.
