### ISSUE TITLE
Games don't have any Options settings like the original cores (Toaplan)

### ISSUE THREAD

**Issue by manichispanic999** [dyreschlock/pocket-extras#22]
Is there a way to alter the Preset files so you can access the options for each game (Button mapping, dip switch settings)?

This is for the Toaplan combined core that you have. 

Thank you!

**Comment by dyreschlock** [comment]
Hrmm...  I checked a couple of the games and all of the options show up for me.  Which specific game isn't working?

All of those settings are determined by the files in the Presets folder. The Presets file must match the exact filename and location of the JSON files in the Assets directory.

**Comment by manichispanic999** [comment]
Looks like I was missing that! Thanks

**Comment by manichispanic999** [comment]
Looks like I was missing that, Thanks!
