### ISSUE TITLE
Vectrex Mod

### ISSUE THREAD

**Issue by dyreschlock** [dyreschlock/pocket-extras#29]
The Vectrex core was recently released, and the core loads both a game and an overlay. It does this separately, and when changing a game, you'd have to switch the game and then switch the overlay.  Also, there's no default blank overlay, besides just turning that option off. Folks suggested using JSON, even though it's a big cumbersome. 

To make it as easy as possible, I thought that the JSON structure could mirror a particular rom-pack and depending on the games, it could reference the overlays as needed. If a game didn't have an overlay, it could use a blank one.

Doing it this way, overall, would allow the user to dump the overlays and the rom-pack in commons, and be ready to go.

**Comment by espiox** [comment]
I found the vast majority of the missing homebrews, they're student projects from the Vectrex Academy. You can find most of the ROMs here in the Academy folders: https://github.com/DrSnuggles/jsvecx/tree/dev/deploy/roms

There are also overlays available for the newer entries in that same GitHub, and some newer ROMs and overlays available here: [2022](https://eitidaten.fh-pforzheim.de/daten/mitarbeiter/johannsen/vectrex_2022/gallery/vectrex_gallery_2022.htm) / [2023](https://eitidaten.fh-pforzheim.de/daten/mitarbeiter/johannsen/vectrex_2023/gallery/vectrex_gallery_2023.htm)

**Comment by dyreschlock** [comment]
Oh nice!  Although, this starts to make my implementation a little more complicated.

Should I just have all of the overlays in the distribution? ...probably

**Comment by espiox** [comment]
Including the overlays might make everything a bit easier (for end-users, at least).

Also I've been looking around this morning and as far as I can tell the games for these overlays are either undumped or unfinished: 3D Pole Position, Spike's Wedding, Stunt Cycle/Stunt Man Stories (same game), Vector Patrol, Vector Pilot

**Comment by dyreschlock** [comment]
Perhaps the best way to do this is to create my own rom distribution on Archive, complete with overlays included. Then I can add all of these other roms into the mix with their overlays and not have the User run around having to figure out what to download.

Also, it seems like Oblivion might take Terminator's approach of putting only the official roms into the distribution. With that approach they'll be using the Oblivion.Vectrex folder. So, I'll make a copy of the core called Oblivion.Vectrex-Extras which should keep all of the extras separate from the main distribution. The JSON in Vectrex-Extras will mirror the rom-pack I'll have on Archive.

(also, with this change, I renamed the entire folder from vectrex-mod to vectrex-extras)

**Comment by dyreschlock** [comment]
Vectrex Extras has been completed and released!

**Comment by espiox** [comment]
Hey, while looking into some Vectrex stuff I stumbled on a page I hadn't seen before with a handful of extra games and overlays: https://eitidaten.fh-pforzheim.de/daten/mitarbeiter/johannsen/vectrex_lab/vectrex_lab.htm

I may have a few more to contribute shortly too, just need to finish sorting through them.

**Comment by dyreschlock** [comment]
Oh that's funny. Rotor, Count Vecula, and Number Cruncher were some of the standouts from the Students games, and they were made by the teacher. :)

Yeah, some of those weren't available from the other pages. Nice find!

**Comment by espiox** [comment]
Okay, here's everything else I've found (all freely available): https://www.mediafire.com/file/t16hkmm29oukage/vectrex_missing.zip/file

Also, I was confused about the multiple versions of Vectorblade (Gold 2, 1.03 etc) and found that it's actually on GitHub, and the latest version is 1.13: https://github.com/malbanGit/Vectorblade (Gold is the version that got pressed to cart, but is older than 1.13, I believe)

**Comment by dyreschlock** [comment]
Have you gotten Vectorblade to actually work on the Pocket? All the versions I've tried just boot into Mine Storm.

**Comment by espiox** [comment]
Nah, I can't get it to work either. I wonder if it works on MiSTer or if it's specific to the Pocket port?

**Comment by dyreschlock** [comment]
This has been finished. Make new cases for updates.
