### ISSUE TITLE
Williams 6809 Combination Core

### ISSUE THREAD

**Issue by dyreschlock** [dyreschlock/pocket-extras#30]
Both Williams 6809 Rev 1 cores have now been released. I put both cores together on my SD card. It's not perfect as I think Jin has a slightly different vertical resolution that the Rev 2 vertical games. I can upload it into extras, along with all the extra games.

We can figure out what to do with it later.

**Comment by espiox** [comment]
I wonder how hard it would be to adjust which video slots are referenced in each core, so the video.json could be merged together? I’d like to look into that but I have no idea how I’d then make the RBF file.

**Comment by dyreschlock** [comment]
You can take a look at what I uploaded. The only game that had troubles with was Playball, so I didn't include it.

**Comment by dyreschlock** [comment]
The video.json for Defender and Robotron match up pretty closely.  Both 0 slots are the same. The 1 slot is just SLIGHTY different. For Defender the height is 236, and for Robotron, it's 232. I set the combo core one to 232, which I think cuts off Jin just a little bit. Defender has a 2 slot, which Robotron does not.

It's pretty close. 

I don't plan on making a release with it because it's not perfect, and may not be perfect. Obsidian would have to make some changes and lock everything together.

**Comment by dyreschlock** [comment]
This is now included in releases. I'm closing this.
