### ISSUE TITLE
Update the Toaplan V2 Combo cores

### ISSUE THREAD

**Issue by manichispanic999** [dyreschlock/pocket-extras#35]
The Toaplan cores were updated, can the combo cores be updated as well? Thank you

**Comment by dyreschlock** [comment]
Hi there. 

I've been super busy these past couple of weeks and I'll probably be busy through the next week or so.  So, I haven't been able to give my full attention to pocket-extras.

But, I did update the Toaplan v2 Core with Teki Paki. I just haven't made a release yet. I still needed to go through Jotego updates for the 1942/1943 core to get everything up to date there. The Vectrex core is behind, too.

**Comment by dyreschlock** [comment]
I've been working on getting the 1942/1943 core up to date and including some rom hacks I found.  Once I'm done with that, I'll make a release.  I'll do Vectrex later.

**Comment by manichispanic999** [comment]
> I've been working on getting the 1942/1943 core up to date and including some rom hacks I found. Once I'm done with that, I'll make a release. I'll do Vectrex later.

Thank you for all your work!

I'm in no rush for any of this btw, this "issue" is just a reminder.

**Comment by dyreschlock** [comment]
Alrighty. This has been released! :)

**Comment by manichispanic999** [comment]
Thank you!
