### ISSUE TITLE
obsidian.Vectrex-Extras .json download

### ISSUE THREAD

**Issue by AnotherPocket** [dyreschlock/pocket-extras#37]
Hello. I prefer to update my Pocket 1 file at a time. I do not use updating software or file grabbing software. With this said, I've found your ROM archive but it does not contain the .json files. For me to get them, I would need to click and download over 1,000 files from your github. Is there a full .zip of your .json files I could get from somewhere? Thank you!

Thank you for your efforts.

**Comment by dyreschlock** [comment]
Hi there.

Click on the Releases category on the side of the main page, and download the Vectrex extras zip. That will have everything you need. :)

**Comment by AnotherPocket** [comment]
I found it. Thank you very much!
