### ISSUE TITLE
ROMs not loading... (help please)

### ISSUE THREAD

**Issue by AnotherPocket** [dyreschlock/pocket-extras#38]
I am using pocket-extras-vectrex-v2.5.1. I have the bitstream.rbf_r in the obsidian.Vectrex-Extras folder. I have the ROM set from Archive. When I run a .json file the correct overlay loads, but the screen is always black. It is as if the ROMs are not loading. I do not see any errors, etc. I am confident everything is where it needs to be. 

I have removed everything and then put it all back on more than once. I wiped the CACHE between testing as well. I'm not sure what the issue is and was hoping you could provide some insight.

This is the only Vectrex core I have installed. I removed the original because I have no reason to switch between the two. I just want to use your fork. 

Thank you!

**Comment by dyreschlock** [comment]
Hmm....  I'll take a look in a little bit.

One thing to note: I have not yet checked if everything works with version v0.9.4 of Obsidian's Vectrex core. I'm not exactly sure what changed between v0.9.1 and v0.9.4 that may cause problems. Currently Vectrex extra has only been tested with version v0.9.1.

You could try downloading v0.9.1, copy over that bitstream, and see if that works?
https://github.com/obsidian-dot-dev/openFPGA-Vectrex/releases/tag/v0.9.1

If it still doesn't work, then something could be goofy with your set up.

**Comment by dyreschlock** [comment]
Hmm... I'm not sure how relevant this is, but could I get some more information?
1. Are you currently running version 2.2 of the OS?
2. When did you get your Analogue Pocket? Have you had one since launch or recently received one? Are you using one of the Limited Editions?
3. Also curious, what other cores do you have installed on your Pocket?

**Comment by AnotherPocket** [comment]
Hey. Thank you! That was the problem! I really appreciate your help and your quick response. You're hard work is allowing me to enjoy hundreds of Vectrex games I otherwise never would have been able to experience! 

Off-topic... I wanted to point you to a collection of Game Boy Advance homebrew files that would benefit your gba-games  project. Is there a way I can send you a link? It's currently on The Way Back Machine because the original site was removed by the admins (taking with it 8 years of preservation and a lot of hard work).

**Comment by AnotherPocket** [comment]
> Hmm... I'm not sure how relevant this is, but could I get some more information?
> 
>     1. Are you currently running version 2.2 of the OS?
> 
>     2. When did you get your Analogue Pocket? Have you had one since launch or recently received one? Are you using one of the Limited Editions?
> 
>     3. Also curious, what other cores do you have installed on your Pocket?

I am using v2.2 of the OS. My Pocket is the translucent green from the limited run that shipped late November 2023. I have a lot of cores installed, like most of what is available (85 arcade, 1 computer, 14 console, 11 handheld). I installed everything by hand, one at a time, over the past few months. The only issue I've run into so far was Atari System 1. It caused some artifacts and pixel issues. This was fixed in the most recent update.

**Comment by dyreschlock** [comment]
Oh nice. So everything works with v0.9.1 of the core?

That's a bit annoying that things break in v0.9.4. I wonder how things changed....  oh, actually. I think the biggest change was moving the bios outside of the compiled core. So, maybe it didn't work for you in v0.9.4 because you didn't have the bios file. (I don't remember the details)

Anyways, that's great that everything works 😃 

____

I think you sent me a Twitter message about those GBA games. My repo dyreschlock/gba-games is a Fork, so it's just a copy. Here's the original repo:
https://github.com/gbadev-org/games

**Comment by AnotherPocket** [comment]
Yes, that was my message. Thank you for the link. I'll follow up there.

**Comment by AnotherPocket** [comment]
> That's a bit annoying that things break in v0.9.4. I wonder how things changed.... oh, actually. I think the biggest change was moving the bios outside of the compiled core. So, maybe it didn't work for you in v0.9.4 because you didn't have the bios file. (I don't remember the details)

I just added the bios file into the common folder and the 0.9.4 bitstream.rbf_r, and that produced the same issue as before.

**Comment by dyreschlock** [comment]
I'd need to update the data.json or some file so it knows where to look.

**Comment by AnotherPocket** [comment]
If you make any changes and need me to test, please let me know.

**Comment by dyreschlock** [comment]
There is other stuff that needed changing to fully update to 0.9.4.  This is being done is case #32
