### ISSUE TITLE
Vectrex-extras v2.7.0 // Sept 5th Release (Erroring)

### ISSUE THREAD

**Issue by AnotherPocket** [dyreschlock/pocket-extras#41]
Hello,
I noticed the old release (2.6.0) has 'Settings\obsidian.Vectrex-Extras' folder and the new release (2.7.0) does not. Should I delete this folder now?

Thank you for your help.

**Comment by dyreschlock** [comment]
Are you still getting errors?

I don't think the settings should matter when updating a core. Everything in there is generated anyways, so you could just delete it or move it elsewhere for testing.

**Comment by dyreschlock** [comment]
In addition to the files listed in the game's JSON file, the data.json also lists needed files for booting. File ID [3] is the Vectrex Bios.

**Comment by AnotherPocket** [comment]
Sorry. I came back to edit but it looks like I didn't beat you! LOL. The error was caused by the missing BIOS file. I remember we discussed that previously, and after recalling that and adding it, my error went away!

Cheers!

**Comment by AnotherPocket** [comment]
Sorry. I came back to edit but it looks like I didn't beat you! LOL. The error was caused by the missing BIOS file. I remember we discussed that previously, and after recalling that and adding it, my error went away!

Cheers!
