### ISSUE TITLE
Can the Capcom z80 combined cores be updated to have the new Avengers game?

### ISSUE THREAD

**Issue by manichispanic999** [dyreschlock/pocket-extras#42]
jotego updated his Trojan core for a new game called Avengers, can you update the capcom z80 combined core to allow the new game? Thank you

**Comment by dyreschlock** [comment]
I did add the files and everything to the repo. I have not tested anything yet.

**Comment by manichispanic999** [comment]
1942 has an update now too

**Comment by dyreschlock** [comment]
I'm gonna work on this today :)

**Comment by manichispanic999** [comment]
gracias

**Comment by dyreschlock** [comment]
Everything has been updated in the code and tested.  I'm going to look at another thing or two before I make a new release.

**Comment by dyreschlock** [comment]
Okey dokey. This has been released. :)
